apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-kecp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-kecp@sha256:0b3c9d1f65527a40376674b68093c0cf13c6672ca9ebf6172f38c19d7bd74911
        name: my-nodejs
        resources: {}
status: {}
